README.md
=> Ajout du readme

pom.xml
=> Ajout de la dependance a Picocli

code_of_conduct.md
=> code_of_conduct

portfolio.md
=> Rédaction du portfolio

CODE_OF_CONDUCT.md
=> Création CODE_OF_CONDUCT.md NEW

.gitignore
Closes #27 
A valider après #26
=> Modification du gitignore

src/main/java/ch/heigvd/labo/Main.java, src/main/java/ch/heigvd/labo/command/New.java, src/test/java/ch/heigvd/labo/command/NewTest.java
=> Ajouter la sous-commande Picocli new

src/main/java/ch/heigvd/labo/command/Build.java, src/test/java/ch/heigvd/labo/command/BuildTest.java
=> Ajout commande build + test unitaire

src/main/java/ch/heigvd/labo/command/Serve.java, src/test/java/ch/heigvd/labo/command/ServeTest.java
=> Ajout commande Serve + test unitaire

src/main/java/ch/heigvd/labo/Main.java, src/main/java/ch/heigvd/labo/command/Clean.java, src/test/java/ch/heigvd/labo/command/CleanTest.java
=> Ajouter la sous-commande Picocli clean

src/main/java/ch/heigvd/labo/Main.java
=> Modifier le main pour accepter les sous-commandes

.gitignore
=> Modifier le gitignore

pom.xml, src/test/java/ch/heigvd/labo/MainTest.java, src/test/java/ch/heigvd/labo/command/BuildTest.java, src/test/java/ch/heigvd/labo/command/CleanTest.java, src/test/java/ch/heigvd/labo/command/NewTest.java, src/test/java/ch/heigvd/labo/command/ServeTest.java
=> Modification des fichiers pour accepter la dépendance jUnit

pom.xml, src/main/java/ch/heigvd/labo/Main.java, src/test/java/ch/heigvd/labo/MainTest.java
=> Ajout de la version en cours

pom.xml, src/main/java/ch/heigvd/labo/Main.java
=> Modification affichage version

pom.xml, src/main/java/ch/heigvd/labo/Main.java, src/main/java/ch/heigvd/labo/command/Init.java, src/test/java/ch/heigvd/labo/command/InitTest.java
=> Ajout de la commande init + modifier pom.xml

.gitignore, src/main/java/ch/heigvd/labo/command/Init.java, src/test/java/ch/heigvd/labo/command/InitTest.java
=> Modification init test et modif gitignore

src/main/java/ch/heigvd/labo/command/Clean.java, src/test/java/ch/heigvd/labo/command/CleanTest.java
=> [TOREVIEW] Implémentation de clean en cours

src/test/java/ch/heigvd/labo/MainTest.java
=> [TOREVIEW] Ajout d'un test unitaire pour la version

README.md
Ajout du clean
Concerne issue #47
=> [TOREVIEW] Issue47 doc2

src/main/java/ch/heigvd/labo/Utility.java, src/main/java/ch/heigvd/labo/command/New.java, src/test/java/ch/heigvd/labo/command/NewTest.java
Implémentation de la sous-commande New
=> [TOREVIEW] Format des pages

src/test/java/ch/heigvd/labo/command/NewTest.java
=> Test avec un test erroné

src/test/java/ch/heigvd/labo/command/NewTest.java
Reverts gen-classroom/projet-dgpw#70
=> Revert "Test avec un test erroné"

src/main/java/ch/heigvd/labo/command/Init.java, src/test/java/ch/heigvd/labo/command/InitTest.java
=> [TOREVIEW] Ajout de la création de fichier de conf

README.md
=> [TOREVIEW] Ajout de la commande new au README

src/main/java/ch/heigvd/labo/command/New.java, src/test/java/ch/heigvd/labo/command/NewTest.java
=> [TOREVIEW] Ajout des tests unitaires

src/main/java/ch/heigvd/labo/Utility.java, src/main/java/ch/heigvd/labo/command/Init.java
=> [TOREVIEW] Ajout index.md dans INIT

src/main/java/ch/heigvd/labo/Utility.java, src/main/java/ch/heigvd/labo/command/Build.java, src/main/java/ch/heigvd/labo/command/Clean.java, src/main/java/ch/heigvd/labo/command/Init.java, src/test/java/ch/heigvd/labo/command/BuildTest.java, src/test/java/ch/heigvd/labo/command/CleanTest.java, src/test/java/ch/heigvd/labo/command/InitTest.java
=> [TOREVIEW] Adapater les commandes

pom.xml
=> [TOREVIEW] Mise à jour de la version dans le pom

pom.xml, src/main/java/ch/heigvd/labo/Main.java, src/main/java/ch/heigvd/labo/Utility.java, src/main/java/ch/heigvd/labo/command/Build.java, src/main/java/ch/heigvd/labo/command/Init.java, src/main/java/ch/heigvd/labo/command/New.java, src/test/java/ch/heigvd/labo/MainTest.java, src/test/java/ch/heigvd/labo/command/BuildTest.java, src/test/java/ch/heigvd/labo/command/CleanTest.java, src/test/java/ch/heigvd/labo/command/InitTest.java, src/test/java/ch/heigvd/labo/command/ServeTest.java
=> [TOREVIEW] Nettoyage code

src/main/java/ch/heigvd/labo/command/Build.java, src/main/java/ch/heigvd/labo/command/Clean.java, src/main/java/ch/heigvd/labo/command/Init.java, src/main/java/ch/heigvd/labo/command/New.java
=> [TOREVIEW] Relève les erreurs de paramètre

src/main/java/ch/heigvd/labo/command/Build.java, src/main/java/ch/heigvd/labo/command/Clean.java, src/test/java/ch/heigvd/labo/command/CleanTest.java
=> [TOREVIEW] Correction clean

README.md
Closes #47 
- Le README a été mis à jour selon les commandes présentes 
- La release a été mise à disposition
=> [TOREVIEW] Mise à jour des commandes du readme

src/main/java/ch/heigvd/labo/Utility.java, src/main/java/ch/heigvd/labo/command/Init.java
=> Création des fichiers menu.html et layout.html

src/main/java/ch/heigvd/labo/Utility.java, src/main/java/ch/heigvd/labo/command/Clean.java, src/main/java/ch/heigvd/labo/command/Serve.java
=> [TOREVIEW] Visualiser page - Serveur HTTP

src/main/java/ch/heigvd/labo/command/Build.java, src/main/java/ch/heigvd/labo/command/Clean.java, src/main/java/ch/heigvd/labo/command/Init.java, src/main/java/ch/heigvd/labo/command/New.java, src/main/java/ch/heigvd/labo/command/Serve.java, src/test/java/ch/heigvd/labo/command/BuildTest.java, src/test/java/ch/heigvd/labo/command/CleanTest.java, src/test/java/ch/heigvd/labo/command/InitTest.java, src/test/java/ch/heigvd/labo/command/NewTest.java, src/test/java/ch/heigvd/labo/command/ServeTest.java
=> [WIP] Modification des tests unitaires 

README.md, src/main/java/ch/heigvd/labo/command/Serve.java
=> [TOREVIEW] Modifications du README

pom.xml
Closes #116 
1. Lancer les tests
2. Vérifier que le fichier jacoco.exec est bien situé dans target/
3. Dans IntelliJ : Run > Show Code Coverage > Sélectionner jacoco.exec
4. Lire dans le browser le *report* de JaCoCo
=> [TOREVIEW] Code Coverage avec JaCoCo

pom.xml
Closes #115
/!\ Vérifier que la variable $JAVA_HOME est bien set. 
Puis : mvn javadoc:javadoc
=> [TOREVIEW] Implémentation de Javadoc

README.md
=> [TOREVIEW] Modifs readme OK
